import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import Footer from "@/components/Footer";
import Navbar from "@/components/client/Navbar";

const inter = Inter({ subsets: ["latin"] });

const ApolloWrapper = dynamic(
  () => import("../components/client/ApolloWrapper"),
  { ssr: false }
);

export const metadata: Metadata = {
  title: "Home | Search Pokemon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <Navbar />
          {children}
          <Footer />
        </ApolloWrapper>
      </body>
    </html>
  );
}
